---
# tasks file for redis
  - name: Setup redis repo file as a rpm
    yum: 
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: installed
      disable_gpg_check: true

  - name: Enable Redis 6.2
    command: 'yum module enable redis:remi-6.2 -y'

  - name: Install Redis
    yum: 
      name: redis
      state: installed

  - name: Update listen address
    replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: "Start & Enable {{component}} Service"
    import_role:
      name: common
      tasks_from: restart-service
