---
# tasks file for user
  - name: Install NodeJS 
    import_role:
      name: common
      tasks_from: nodejs

  - name: App Setup
    import_role:
      name: common
      tasks_from: app-setup

  - name: Install NPM 
    import_role:  
      name: common
      tasks_from: npm-install
      
  - name: Systemd Setup & Start service
    import_role:
      name: common
      tasks_from: systemd-setup

  - name: Load Schema
    import_role:
      name: common
      tasks_from: load-mongodb-schema