---
# tasks file for catalogue

  - name: Install NodeJS 
    import_role:
      name: common
      tasks_from: nodejs
  - name: App Setup
    import_role:
      name: common
      tasks_from: app-setup


  