---
# tasks file for common
  - name: Setup NodeJS repos
    shell: 'curl -sL https://rpm.nodesource.com/setup_lts.x | bash'
      
  - name: Install NodeJS
    yum:
      name: nodejs
      state: installed