  - name: "Setup SystemD {{component}} Service"
    template:
      src: "{{component}}.service.j2"
      dest: "/etc/systemd/system/{{component}}.service"

  - name: Load the daemon service
    systemd:
      daemon-reload: true
  
  - name: "Start the {{component}} service"
    service:
      name: "{{component}}"
      state: started
      enabled: true